### ISSUE TITLE
Support for M2 Mac?

### ISSUE THREAD

**Issue by rinaldiap** [Nicholaswogan/NumbaMinpack#7]
I was trying to use the library on a M2 Mac and I noticed they file libminpack.dylib is not compatible with the architecture (have 'x86_64', need 'arm64')

**Comment by Nicholaswogan** [comment]
It should work OK for M2 mac as along as you have Fortran and C compilers on your machine.

**Comment by rinaldiap** [comment]
Indeed it was an issue on my side. I had the compiler installed with a x86_64 version of homebrew.

**Comment by rinaldiap** [comment]
Indeed it was an issue on my side. I had the compiler installed with a x86_64 version of homebrew.
